### ISSUE TITLE
not showing up when clicking + under integration

### ISSUE THREAD

**Issue by bbrendon** [KoljaWindeler/ics#10]
1. installed with HACS, checked the ics directory exists under custom_components.
2. restarted hass.
3. Tried to set it up with the GUI, it doesn't show up. I looked for "ICS".

**Comment by KoljaWindeler** [comment]
Hmm, anything in the log?

**Comment by bbrendon** [comment]
No, I checked for something interesting in the log and didn't find anything.

**Comment by KoljaWindeler** [comment]
I've just spun up a blank homeassistant docker image with just ICS in it. Shows up at the integration menu and loads without any issue. 

Kolja
