### ISSUE TITLE
Platform error sensor.ics - No module named 'tzlocal'

### ISSUE THREAD

**Issue by bbrendon** [KoljaWindeler/ics#11]
I tried to configure manually. Fails.

```
# hacheck
Testing configuration at /opt/hass-prod-cfg
Failed config
  General Errors:
    - Platform error sensor.ics - No module named 'tzlocal'

Successful config (partial)
#

```

**Comment by KoljaWindeler** [comment]
hmm what version are you using? HA and ics? 
tzlocal is a dependency that should have been installed during bootup

I've just spun up a blank homeassistant docker image with just ICS in it. Shows up at the integration menu and loads without any issue. 

Kolja

**Comment by bbrendon** [comment]
Got it. I won't open issues.
