### ISSUE TITLE
Contains Filter

### ISSUE THREAD

**Issue by vbtrek** [KoljaWindeler/ics#15]
Hi, could you add a new filter to do a Contains search, behaves just like the startswith but does a contains search. I have a holiday calendar and I only want to pull in the entries that have Holiday in the appointment title.

Thanks

**Comment by KoljaWindeler** [comment]
I'll have a look and get back to you.
Kolja

**Comment by KoljaWindeler** [comment]
Hi, have a look at https://github.com/KoljaWindeler/ics/commit/a7c2824290b0c6149eb192de6293f839349a9b2d
that should add your filter. After updating (and a restart of HA?) you have to create a **new** sensor to use the contains filter.  
Let me know if it works for you
Kolja

**Comment by vbtrek** [comment]
Excellent, so fast. I'll get it installed when it appears in HACS and let you know how it goes. Thanks

**Comment by vbtrek** [comment]
Will this update get published into HACS? I've not seen an update appear yet

**Comment by KoljaWindeler** [comment]
hmm honestly .. I don't understand why HACS shows version 0.4 .. I don't see where I've set the version .. I'll keep looking

**Comment by vbtrek** [comment]
Got the update and given it a test but getting the following error logged:
2020-10-05 13:51:36 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for ics doing I/O at custom_components/ics/const.py, line 237: return requests.get(url, headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36'}, allow_redirects=True).content

The calendar is published by kayak.co.uk trips feed, so the issue may be with their ics file.

**Comment by KoljaWindeler** [comment]
No no that warning is supposed to show up. No worries. That only happens once during setup. It depends on the way how I grab the file. That's synchronous during setup and asynchronous later one. 


Does the contains filter work as expected?
Kolja

**Comment by vbtrek** [comment]
Yep, the contains is working a treat. Thanks

**Comment by KoljaWindeler** [comment]
Great
