### ISSUE TITLE
failure (-999)

### ISSUE THREAD

**Issue by felixbro** [KoljaWindeler/ics#17]
Hello,
i get a "failure (-999)" in my lovelace-card and cant find a solution.
its a local ics file and there are dates in the future.

can anybody help?

**Comment by KoljaWindeler** [comment]
are you using file:///confiig/... or http://yourip:8123/local/file ?
The external link has more issues, so the file:///config/www/myfile.ics works better .. and faster .. can you try that? 
Also can you provide more info, like where do you store the file .. is that folder in the allowed directory list of homeassistant etc?
Thanks, Kolja

**Comment by felixbro** [comment]
I didn't know that you have to put three `/` after `file:`.
the path is now: `file:///config/www/mycalender.ics`.
I had read it in the Configuration options, but for some reason thought it was a typo.
now everything works.

Thank you.
