### ISSUE TITLE
Version key needs to be included before june

### ISSUE THREAD

**Issue by wormiedk** [KoljaWindeler/ics#27]
This message is shown in the log :
No 'version' key in the manifest file for custom integration 'ics'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'ics'

**Comment by gettech** [comment]
Same issue here, ICS stopped working

**Comment by KoljaWindeler** [comment]
That was fixed a while back.   https://github.com/KoljaWindeler/ics/releases/tag/0.5.0

You have to update the integration
