### ISSUE TITLE
Integration Causing Stability Issues

### ISSUE THREAD

**Issue by ColoradoBills** [KoljaWindeler/ics#28]
Error when trying to add the Integration to latest build of HA OS Supervised. 

Logger: homeassistant.util.async_
Source: util/async_.py:132 
First occurred: 2:46:21 AM (1 occurrences) 
Last logged: 2:46:21 AM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for ics doing I/O at custom_components/ics/const.py, line 239: return requests.get(url, headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36'}, allow_redirects=True).content

My HA Build:
## System Health

version | core-2021.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | America/Denver

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4914
Installed Version | 1.12.4
Stage | running
Available Repositories | 889
Installed Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | June 15, 2021, 6:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.05.4
docker_version | 19.03.15
disk_total | 109.3 GB
disk_used | 6.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | deCONZ (6.9.0), Check Home Assistant configuration (3.7.1), File editor (5.3.1), AirSonos (3.1.0), ESPHome (1.18.0), InfluxDB (4.1.1), Grafana (6.3.5), Visual Studio Code (3.4.1), Log Viewer (0.11.0), SSH & Web Terminal (8.2.3), Home Assistant Google Drive Backup (0.104.3), AirCast (3.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 14
views | 3
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by KoljaWindeler** [comment]
should be fixed
