### ISSUE TITLE
"Unable to serialize to JSON: Object of type coroutine is not JSON serializable" in config flow

### ISSUE THREAD

**Issue by Flop2006** [KoljaWindeler/ics#30]
I got this Error when i try to generate a new sensor via config flow:

`Unknown error occurred`

In the log is see this error:

`Unable to serialize to JSON: Object of type coroutine is not JSON serializable {'type': 'form', 'flow_id': '6483a2b274534cf4b5b9dc3eab38e7e2', 'handler': 'ics', 'step_id': 'user', 'data_schema': [{'type': 'string', 'name': 'name', 'required': True, 'default': 'Muell'}, {'type': 'string', 'name': 'url', 'required': True, 'default': 'file:///config/www/calendar/2021-1610610101.ics'}, {'type': 'integer', 'name': 'id', 'required': True, 'default': 6}, {'type': 'string', 'name': 'timeformat', 'optional': True, 'default': '%A, %d.%m.%Y'}, {'type': 'string', 'name': 'startswith', 'optional': True, 'default': 'test'}, {'type': 'string', 'name': 'contains', 'optional': True, 'default': 'test'}, {'type': 'integer', 'name': 'lookahead', 'optional': True, 'default': 7}, {'type': 'string', 'name': 'icon', 'optional': True, 'default': 'mdi:calendar'}], 'errors': <coroutine object check_data at 0x7f0d152cebc0>, 'description_placeholders': None}`

If i configure this sensor by hand it works flawless.

**Comment by KoljaWindeler** [comment]
yep, that was recently messed up, will release a fix shortly
