### ISSUE TITLE
Problem with all day events

### ISSUE THREAD

**Issue by Friedi1970** [KoljaWindeler/ics#32]
I have an automation where I use the following script for an output to a notification:

```
       {% if is_state_attr("sensor.ics_1", "remaining",1) and is_state_attr("sensor.ics_1", "description",'Sperrmüllanmeldung') -%}
       Morgen ist die letzte Möglichkeit für die {{states.sensor.ics_1.attributes.description}}.
       {%- elif is_state_attr("sensor.ics_1", "remaining",1) -%} {{states.sensor.ics_1.attributes.description}} wird morgen abgeholt.{%- endif -%}
```
The thing is, it doesn‘t work if the automation runs on a day which has already an all day appointment because the remaining attribute is 0. So it doesn‘t fire the message for the next day event.

I am not an expert and I really have a problem solving this problem. How to deal with this problem?

**Comment by KoljaWindeler** [comment]
Hmm ich würde sagen du erstellt einfach mehrere entities mit jeweils einem Filter? Ginge das? 
Damit sollte das dann ja "zerlegt" sein, zumindest mache ich das so mit meinem Kalender der auch alle Müllsorten beinhaltet

**Comment by Friedi1970** [comment]
Ha, da hat tatsächlich jemand bemerkt, dass ich deutscher Natur bin ;)

Danke erst mal für die verdammt schnelle Antwort. Du meinst, dass ich das den ICS aufteile und mehrere Kalender daraus mache? Das war auch mein Gedanke, dachte aber, dass es vielleicht einen anderen Ansatz gibt.

**Comment by KoljaWindeler** [comment]
ne gar nicht mal .. aber was ist den im Kalender drin? ich hab einen von meinen Stadtwerken der hat alle muellsorten gemischt.
daraus hab ich 3 ICS entities gemacht (einfach 3x die integration angelegt immer mit dem gleichen file).
Bei jedem mal Anlegen hab ich in den Filter geschrieben was er raussuchen soll .. also 1. mal anlegen "restm" (wollte mich nicht mit den Sonderzeichen rumaergern) beim 2. "gelber sack" etc ... verstehst? 

PS: Ja das war aber nicht sooo schwer :D

**Comment by Friedi1970** [comment]
🤔 du meinst einfach mit startswith?

> PS: Ja das war aber nicht sooo schwer :D

🤣

**Comment by KoljaWindeler** [comment]
jepp

**Comment by Friedi1970** [comment]
Manchmal kann es so einfach sein 👍 Danke dir für die schnelle und pragmatische Inspiration!

**Comment by KoljaWindeler** [comment]
fein, ich mach das hier dann mal zu. kannst es ja wieder aufmachen wenns probleme gibt.
