### ISSUE TITLE
Seit Update auf 2021.08 Fehlermeldung

### ISSUE THREAD

**Issue by Friedi1970** [KoljaWindeler/ics#33]
Leider ich schon wieder ...

Gestern habe ich das Update 2021.8.0 eingespielt und seitdem ist bei der Konfigurationsprüfung folgender Fehler:
Platform error sensor.ics - Integration 'ics' not found.

Neuinstallation über HACS mit Restart per Konsole brachte nichts.

**Comment by Friedi1970** [comment]
Seltsam. Der Ordner ics in custom_components war weg.

**Comment by KoljaWindeler** [comment]
Tjoa, ... 2021.08 läuft reibungslos bei mir ...

**Comment by Friedi1970** [comment]
> Tjoa, ... 2021.08 läuft reibungslos bei mir ...
Jo, bei mir jetzt auch. Warum der Ordner weg war, wird auf ewig ein Rätsel bleiben ...

Btw. Bei mir läuft jetzt alles, wie es soll. Danke noch mal für die schnelle Hilfe!
