### ISSUE TITLE
Pulling in Calendar from Exchange

### ISSUE THREAD

**Issue by entr0p1** [KoljaWindeler/ics#5]
Hi Kolja,

I'm trying out ics with my Exchange 2019 calendar but I'm getting the below error:

24/03/2020 20:43:46Traceback (most recent call last):
24/03/2020 20:43:46  File "/config/custom_components/ics/sensor.py", line 121, in get_data
24/03/2020 20:43:46    cal_string = urlopen(self._url).read().decode('ISO-8859-1')
24/03/2020 20:43:46  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
24/03/2020 20:43:46    return opener.open(url, data, timeout)
24/03/2020 20:43:46  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
24/03/2020 20:43:46    response = meth(req, response)
24/03/2020 20:43:46  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
24/03/2020 20:43:46    'http', request, response, code, msg, hdrs)
24/03/2020 20:43:46  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
24/03/2020 20:43:46    return self._call_chain(*args)
24/03/2020 20:43:46  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
24/03/2020 20:43:46    result = func(*args)
24/03/2020 20:43:46  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
24/03/2020 20:43:46    raise HTTPError(req.full_url, code, msg, hdrs, fp)
24/03/2020 20:43:46urllib.error.HTTPError: HTTP Error 403: Forbidden

I've tested the link directly in my browser and it works fine (the Calendar is set to public). I'm also using the iCal sensor plugin with this same calendar and it's working fine.

Any ideas? I can provide you the link in a private message somehow (just don't want to post it here for all to see)

**Comment by KoljaWindeler** [comment]
Hi, can you send me the link to Kolja.Windeler@gmail.com ?
Thanks

**Comment by entr0p1** [comment]
All done, thanks!

**Comment by KoljaWindeler** [comment]
Your server required a header in the request.
I've added that in https://github.com/KoljaWindeler/ics/commit/19797df1e37a15c01c12fa539a0e4892d65505fa
Kolja
