### ISSUE TITLE
Deprecated -  'ics' sets "data" directly to update a config entry

### ISSUE THREAD

**Issue by duczz** [KoljaWindeler/ics#52]
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:156
Erstmals aufgetreten: 17:57:54 (4 Vorkommnisse)
Zuletzt protokolliert: 17:57:57

Detected that custom integration 'ics' sets "data" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at custom_components/ics/__init__.py, line 19: config_entry.data = ensure_config(config_entry.data, hass) # make sure that missing storage values will be default (const function), please report it to the author of the 'ics' custom integration
Detected that custom integration 'ics' sets "options" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at custom_components/ics/__init__.py, line 20: config_entry.options = config_entry.data, please report it to the author of the 'ics' custom integration
Detected that custom integration 'scheduler' accesses hass.components.websocket_api. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from websocket_api directly at custom_components/scheduler/websockets.py, line 235: hass.components.websocket_api.async_register_command(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by joemcc-90** [comment]
tested and opened a PR here to remove deprecated functions - https://github.com/KoljaWindeler/ics/pull/53
